import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Sidenav from "./components/Sidenav";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/app-assets/images/ico/favicon.ico',
    apple: '/app-assets/images/ico/apple-icon-120.png',
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="pace-running">
        {/* Scripts from /public */}
        <Script src="/app-assets/vendors/js/vendors.min.js" strategy="beforeInteractive" />
        <Script src="/app-assets/vendors/js/charts/apexcharts.min.js" strategy="beforeInteractive" />
        <Script src="/app-assets/vendors/js/extensions/toastr.min.js" strategy="beforeInteractive" />
        <Script src="/app-assets/js/core/app-menu.js" strategy="afterInteractive" />
        <Script src="/app-assets/js/core/app.js" strategy="afterInteractive" />
        <Script src="/app-assets/js/scripts/pages/dashboard-ecommerce.js" strategy="afterInteractive" />
        <Script id="feather-init" strategy="afterInteractive">
          {`
            window.addEventListener('load', function () {
              if (window.feather) {
                window.feather.replace({ width: 14, height: 14 });
              }
            });
          `}
        </Script>
        <Header />
        <Sidenav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
